model_selection:
  model:
    XGBClassifier:
      search_param_grid:
        max_depth:
          - 3
          - 5
          - 7
          - 11
        n_estimators:
          - 50
          - 100
          - 130
        learning_rate:
          - 0.01
          - 0.1
          - 0.2
        subsample:
          - 0.6
          - 0.8
          - 1.0
        colsample_bytree:
          - 0.6
          - 0.8
          - 1.0
        random_state:
          - 0
          - 50
          - 100

    RandomForestClassifier:
      search_param_grid:
        n_estimators:
          - 50
          - 100
          - 200
        max_depth:
          - 5
          - 10
          - 20
          - None
        max_features:
          - 'auto'
          - 'sqrt'
          - 'log2'
        bootstrap:
          - True
          - False
        random_state:
          - 0
          - 50
          - 100
          

    LogisticRegression:
      search_param_grid:
        C:
          - 0.1
          - 1.0
          - 10.0
          - 100.0
        max_iter:
          - 100
          - 200
          - 500
        multi_class:
          - 'auto'
          - 'ovr'
          - 'multinomial'
        penalty:
          - 'l1'
          - 'l2'
        solver:
          - 'lbfgs'
          - 'liblinear'
          - 'saga'

    SVC:
      search_param_grid:
        C:
          - 0.1
          - 1.0
          - 10.0
        kernel:
          - 'linear'
          - 'poly'
          - 'rbf'
          - 'sigmoid'
        gamma:
          - 'scale'
          - 'auto'
        degree:
          - 2
          - 3
          - 4

    DecisionTreeClassifier:
      search_param_grid:
        criterion:
          - 'gini'
          - 'entropy'
        max_depth:
          - None
          - 10
          - 20
          - 30
        min_samples_split:
          - 2
          - 5
          - 10
        min_samples_leaf:
          - 1
          - 2
          - 4
        max_features:
          - None
          - 'auto'
          - 'sqrt'
          - 'log2'
